version: "3.8"

services:
  api:
    container_name: score-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run .

  db:
    container_name: score-api-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=score_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
# networks:
#   default:
#     name: postgre-service_default
volumes:
  postgres-db:
